### ISSUE TITLE
Add `before` property to AST nodes

### ISSUE THREAD

**Issue by desmondmorris** [DFurnes/sasstree#2]
It would be nice to track the leading character much like the trailing character.  There maybe a better way to do this in the pipeline, but I figured I would make note of it here.

An example use case is this BangFormat linter.  I would like to check both the leading and trailing characters around a bang
https://github.com/definerobot/node-scss-lint/blob/es6/src/linters/BangFormat.js#L32

**Comment by DFurnes** [comment]
Would it make sense to make this an alias to the previous node's `after` property? Otherwise I'm not sure where I'd draw the line between "before" and "after" whitespace.

**Comment by desmondmorris** [comment]
+1 thats exactly what I ended up doing actually.

``` javascript
for(let i=0; i<file.ast[0].children.length; i++) {
      let node = file.ast[0].children[i];

      if (node.type === 'BANG') {

        // Hack to add before property
        if (i > 0) {
          let olderSibling = file.ast[0].children[i-1];
          if (typeof olderSibling.after !== 'undefined') {
            node.before = olderSibling.content;
          }
          else {
            node.before = olderSibling.after;
          }
        }
    }
}
```

**Comment by DFurnes** [comment]
Great! :+1: Definitely something that should be added in to the tree.
